#
# docker-compose file for deploying NextCloud in Docker.
#

version: '3.8'
services:
  nextcloud:
    image: nextcloud:28.0.3-apache
    container_name: nextcloud
    hostname: nextcloud.mydomain.com
    environment:
      - TZ="UTC"
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.mydomain.com
      - POSTGRES_DB=nextclouddb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOUR_DB_PASSWORD
      - POSTGRES_HOST=pgsql-db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_DATA_DIR=/opt/nextcloud/data
      - REDIS_HOST=redis
      - PHP_UPLOAD_LIMIT=512M
      - PHP_MEMORY_LIMIT=512M
      # - SMTP_HOST=smtp.mydomain.com
      # - SMTP_SECURE=tls
      # - SMTP_PORT=587
      # - SMTP_AUTHTYPE=login
      # - SMTP_NAME=nextcloud@nextcloud.mydomain.com
      # - SMTP_PASSWORD=SMTP_PASSWORD
      # - MAIL_FROM_ADDRESS=nextcloud
      # - MAIL_DOMAIN=nextcloud.mydomain.com
    volumes:
      - ./nextcloud-data/nextcloud/www:/var/www/html
      - ./nextcloud-data/nextcloud/skeleton:/usr/src/nextcloud/core/skeleton
      - ./nextcloud-data/nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud-data/nextcloud/config:/var/www/html/config
      - ./nextcloud-data/data:/opt/nextcloud/data
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - pgsql-db
  pgsql-db:
    image: postgres:16.1
    container_name: pgsql-db
    environment:
      - TZ="UTC"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOUR_DB_PASSWORD
      - POSTGRES_DB=nextclouddb
    volumes:
      - ./pgsql-db/data:/var/lib/postgresql/data
      - ./pgsql-db/backups:/var/lib/postgresql/backups
      - ./pgsql-db/log:/var/log/postgresql
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  nginx-reverse-proxy:
    image: nginx:1.25.3
    container_name: nginx-reverse-proxy
    environment:
      - TZ="UTC"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/certs:/etc/pki/tls/configs-certs
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
  redis:
    image: redis:7.2.4
    volumes:
      - ./redis-data:/data
    restart: always
    command: redis-server --appendonly yes --auto-aof-rewrite-percentage 20 --auto-aof-rewrite-min-size 200kb

